name: Poke Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - dev
  # workflow_dispatch:
  # schedule:
  #   # Runs at 12am UTC
  #   - cron: '0 0 * * *'

jobs:
  # job 1 testing 4
  add-poke-sprite:
    name: Add Pokemon Sprite to repo README
    runs-on: ubuntu-latest
    steps:
      - uses: ibrahiem96/poke-readme-action@dev/ibrahiem
        with:
          pokemon: 'raichu'
